-- liquibase formatted sql

-- changeset tomharrison:1779794636107-1 splitStatements:false
CREATE TABLE "data_seed_ingestion_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "file_name" VARCHAR(255) NOT NULL,
    "applied_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "checksum" VARCHAR(64) NOT NULL,
    CONSTRAINT "data_seed_ingestion_history_pkey" PRIMARY KEY ("id"));

-- changeset tomharrison:1779794636107-2 splitStatements:false
ALTER TABLE "data_seed_ingestion_history" ADD CONSTRAINT "data_seed_ingestion_history_file_name_key" UNIQUE ("file_name");

