changeLogFile=db.changelog.xml

classpath=.


liquibase.command.url=jdbc:postgresql://localhost:5432/cads_data_service
liquibase.command.username=postgres
liquibase.command.password=postgres

liquibase.command.referenceUrl=jdbc:postgresql://localhost:54432/reference_schema
liquibase.command.referenceUsername=postgres
liquibase.command.referencePassword=postgres
