# Enter the path for your changelog file.
changeLogFile=db.changelog.xml

# The changeLogFile path is relative to the classpath.
classpath=.

# Schema
liquibase.command.liquibaseSchemaName=public

# Target (active) database
liquibase.command.url=jdbc:postgresql://localhost:5432/cads_data_service
liquibase.command.username=postgres
liquibase.command.password=postgres

# Reference (golden) database
liquibase.command.referenceUrl=jdbc:postgresql://localhost:54432/reference_schema
liquibase.command.referenceUsername=postgres
liquibase.command.referencePassword=postgres
