services:
  cads_cds:
    build:
      args:
        TARGETARCH: x64
    labels:
      com.microsoft.visual-studio.project-name: "Cads.Cds"
    environment:
      AWS__ServiceURL: http://cads-localstack:4566
      Postgres__DefaultConnection: Host=cads-postgres;Port=5432;Database=cads_data_service;Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};
      Postgres__ReadOnlyConnection: Host=cads-postgres;Port=5432;Database=cads_data_service;Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres};
      Modules__Ingester__Queues__CadsCds__QueueUrl: http://cads-localstack:4566/000000000000/cads-cds-queue
      Modules__Ingester__Storage__CadsIngester__BucketName: cads-internal-bucket
      Modules__Ingester__Queues__CadsCds__DlqQueueUrl: http://cads-localstack:4566/000000000000/cads-cds-queue-deadletter
      Modules__StorageBridge__Storage__CadsInternal__BucketName: cads-internal-bucket
      Modules__StorageBridge__Storage__CadsInternal__HealthcheckEnabled: "true"
      IMB_S3_ACCESS_KEY: test
      IMB_S3_ACCESS_SECRET: test
      AuthenticationConfiguration__ApiKey__Enabled: "true"
      AuthenticationConfiguration__Cognito__Enabled: "false"
      AuthenticationConfiguration__Cognito__Authority: ""
      AuthenticationConfiguration__AzureAD__Enabled: "true"
      AuthenticationConfiguration__AzureAD__Authority: http://cads-oidc-mock
      AuthenticationConfiguration__AzureAD__Audience: api://local-cads-cds
      AuthenticationConfiguration__AzureAD__MetadataAddress: http://cads-oidc-mock/.well-known/openid-configuration
      AuthenticationConfiguration__AzureAD__RequireHttpsMetadata: "false"
      AuthenticationConfiguration__AzureAD__ValidateIssuer: "false"
    volumes:
      # Mac-specific paths for user secrets and HTTPS certificates
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro

  reference-postgres:
    image: postgres:16.6
    container_name: reference-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_REF_DB}
    ports:
      - "54432:5432"
    volumes:
      - reference-postgres-data:/var/lib/postgresql/data
      - "./compose/postgres/config:/etc/postgres-config"
    command: >
      postgres
        -c config_file=/etc/postgres-config/postgresql.conf
        -c hba_file=/etc/postgres-config/pg_hba.conf
        -c listen_addresses='*'
    networks:
      - cads-tools

  pgadmin:
    image: dpage/pgadmin4:7.8
    user: "root"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pgadmin}
    ports:
      - 16543:80
    volumes:
      - ./compose/postgres/servers:/host:ro
      - pgadmin-data:/var/lib/pgadmin
    entrypoint: ["/host/init.sh"]
    networks:
      - cads-tools

networks:
  cads-tools:
    external: true
  
volumes:
  reference-postgres-data:
  pgadmin-data: