name: 'cads_cds'
services:
  cads_cds:
    container_name: "cads_cds"
    platform: linux
    image: cads_cds
    build: ./
    ports:
      - '5555:5555'
      - '5556:5556'
    volumes:
      - ./static_data:/app/StaticData
      - ./certs:/https:ro
    depends_on: []
    env_file:
      - ./compose/aws.env
      - ./compose/postgres.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5555;https://0.0.0.0:5556"
      ASPNETCORE_HTTP_PORTS: "5555"
      ASPNETCORE_HTTPS_PORTS: "5556"
      Kestrel__Certificates__Default__Path: "/https/https-dev-cert.pfx"
      Kestrel__Certificates__Default__Password: "testpassword"
      PORT: 5555
      LOCALSTACK_ENDPOINT: http://cads-localstack:4566
    networks:
      - cads-tools

  liquibase:
    build:
      context: .
      dockerfile_inline: |
        FROM liquibase/liquibase:5.0.1
        RUN lpm add postgresql --global
        USER liquibase
    depends_on: []
    volumes:
      - ./changelog:/liquibase/changelog
    command: sh -c "liquibase --url=jdbc:postgresql://cads-postgres:5432/${POSTGRES_DB} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --searchPath=/liquibase/changelog --changelog-file=db.changelog.xml --liquibaseSchemaName=public --contexts=${ENV:-none} update && tail -f /dev/null"
    networks:
      - cads-tools

networks:
  cads-tools:
    external: true