// <auto-generated />
// Generated using the HotChocolate GraphQL code generator (see CADS Tools)
// .\cads-tools\codegen\graph-query-generate\Generate-GraphQuery-Resolvers.ps1
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsTransactions.Contexts;
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsTransactions.Entities;
using HotChocolate;
using HotChocolate.Data;
using HotChocolate.Types;
using System.Linq;

namespace Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsTransactions.Queries;

[ExtendObjectType("Query")]
public partial class CtsTransactionsGraphQuery
{   
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAddress> GetCtAddresses([Service] CtsTransactionsGraphQLDbContext db) => db.CtAddresses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAllocRoutine> GetCtAllocRoutines([Service] CtsTransactionsGraphQLDbContext db) => db.CtAllocRoutines;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalChange> GetCtAnimalChanges([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalChanges;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalClaim> GetCtAnimalClaims([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalClaims;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalCorrSummError> GetCtAnimalCorrSummErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalCorrSummErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalCorrectSummary> GetCtAnimalCorrectSummaries([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalCorrectSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalIdentifier> GetCtAnimalIdentifiers([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalRelationship> GetCtAnimalRelationships([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalRelationships;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalStatus> GetCtAnimalStatuses([Service] CtsTransactionsGraphQLDbContext db) => db.CtAnimalStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtApplicStatus> GetCtApplicStatuses([Service] CtsTransactionsGraphQLDbContext db) => db.CtApplicStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtApplicationLateDay> GetCtApplicationLateDays([Service] CtsTransactionsGraphQLDbContext db) => db.CtApplicationLateDays;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtBatchRetentionConf> GetCtBatchRetentionConfs([Service] CtsTransactionsGraphQLDbContext db) => db.CtBatchRetentionConfs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtBreed> GetCtBreeds([Service] CtsTransactionsGraphQLDbContext db) => db.CtBreeds;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtract> GetCtClaExtracts([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtractDetail> GetCtClaExtractDetails([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaExtractDetails;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtractDm> GetCtClaExtractDms([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaExtractDms;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaMiniDetail> GetCtClaMiniDetails([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaMiniDetails;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaMiniExtract> GetCtClaMiniExtracts([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaMiniExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaimStatus> GetCtClaimStatuses([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaimStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaimType> GetCtClaimTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtClaimTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCmAuthority> GetCtCmAuthorities([Service] CtsTransactionsGraphQLDbContext db) => db.CtCmAuthorities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCmMeasuresResult> GetCtCmMeasuresResults([Service] CtsTransactionsGraphQLDbContext db) => db.CtCmMeasuresResults;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCommsAddress> GetCtCommsAddresses([Service] CtsTransactionsGraphQLDbContext db) => db.CtCommsAddresses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCondVariantGrouping> GetCtCondVariantGroupings([Service] CtsTransactionsGraphQLDbContext db) => db.CtCondVariantGroupings;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCondition> GetCtConditions([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionActivity> GetCtConditionActivities([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditionActivities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionMarker> GetCtConditionMarkers([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditionMarkers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionMarkerError> GetCtConditionMarkerErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditionMarkerErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionType> GetCtConditionTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditionTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionVariant> GetCtConditionVariants([Service] CtsTransactionsGraphQLDbContext db) => db.CtConditionVariants;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCountiesMigration> GetCtCountiesMigrations([Service] CtsTransactionsGraphQLDbContext db) => db.CtCountiesMigrations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCountry> GetCtCountries([Service] CtsTransactionsGraphQLDbContext db) => db.CtCountries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCounty> GetCtCounties([Service] CtsTransactionsGraphQLDbContext db) => db.CtCounties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCps167Report> GetCtCps167Reports([Service] CtsTransactionsGraphQLDbContext db) => db.CtCps167Reports;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCts164HandshakeFileKey> GetCtCts164HandshakeFileKeys([Service] CtsTransactionsGraphQLDbContext db) => db.CtCts164HandshakeFileKeys;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCtsUser> GetCtCtsUsers([Service] CtsTransactionsGraphQLDbContext db) => db.CtCtsUsers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartag> GetCtEartags([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartags;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagFormat> GetCtEartagFormats([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartagFormats;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagReason> GetCtEartagReasons([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartagReasons;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagReasonFlag> GetCtEartagReasonFlags([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartagReasonFlags;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagStaging> GetCtEartagStagings([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartagStagings;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagType> GetCtEartagTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtEartagTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtElectronicIdentifier> GetCtElectronicIdentifiers([Service] CtsTransactionsGraphQLDbContext db) => db.CtElectronicIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEmailLog> GetCtEmailLogs([Service] CtsTransactionsGraphQLDbContext db) => db.CtEmailLogs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportFile> GetCtEreportFiles([Service] CtsTransactionsGraphQLDbContext db) => db.CtEreportFiles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportLoadMessage> GetCtEreportLoadMessages([Service] CtsTransactionsGraphQLDbContext db) => db.CtEreportLoadMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportLock> GetCtEreportLocks([Service] CtsTransactionsGraphQLDbContext db) => db.CtEreportLocks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportProcessMessage> GetCtEreportProcessMessages([Service] CtsTransactionsGraphQLDbContext db) => db.CtEreportProcessMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtExtCetdEartag> GetCtExtCetdEartags([Service] CtsTransactionsGraphQLDbContext db) => db.CtExtCetdEartags;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtExtNiDistrict> GetCtExtNiDistricts([Service] CtsTransactionsGraphQLDbContext db) => db.CtExtNiDistricts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtExtSpecialHerd> GetCtExtSpecialHerds([Service] CtsTransactionsGraphQLDbContext db) => db.CtExtSpecialHerds;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtFileLayout> GetCtFileLayouts([Service] CtsTransactionsGraphQLDbContext db) => db.CtFileLayouts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtHsfSequence> GetCtHsfSequences([Service] CtsTransactionsGraphQLDbContext db) => db.CtHsfSequences;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtInsertUpdateLog> GetCtInsertUpdateLogs([Service] CtsTransactionsGraphQLDbContext db) => db.CtInsertUpdateLogs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtIssuedDocument> GetCtIssuedDocuments([Service] CtsTransactionsGraphQLDbContext db) => db.CtIssuedDocuments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtIssuingAuthority> GetCtIssuingAuthorities([Service] CtsTransactionsGraphQLDbContext db) => db.CtIssuingAuthorities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLabelRequest> GetCtLabelRequests([Service] CtsTransactionsGraphQLDbContext db) => db.CtLabelRequests;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLabelSummary> GetCtLabelSummaries([Service] CtsTransactionsGraphQLDbContext db) => db.CtLabelSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLateDay> GetCtLateDays([Service] CtsTransactionsGraphQLDbContext db) => db.CtLateDays;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLetter> GetCtLetters([Service] CtsTransactionsGraphQLDbContext db) => db.CtLetters;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocTypeRelComb> GetCtLocTypeRelCombs([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocTypeRelCombs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocation> GetCtLocations([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationIdFormat> GetCtLocationIdFormats([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationIdFormats;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationIdentifier> GetCtLocationIdentifiers([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationPartyRel> GetCtLocationPartyRels([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationPartyRels;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationPartyRelType> GetCtLocationPartyRelTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationPartyRelTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationRelType> GetCtLocationRelTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationRelTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationRelationship> GetCtLocationRelationships([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationRelationships;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationType> GetCtLocationTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationsFaker> GetCtLocationsFakers([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocationsFakers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocrestrictionstoanimal> GetCtLocrestrictionstoanimals([Service] CtsTransactionsGraphQLDbContext db) => db.CtLocrestrictionstoanimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMgtControlError> GetCtMgtControlErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtMgtControlErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMgtWgAllocationRule> GetCtMgtWgAllocationRules([Service] CtsTransactionsGraphQLDbContext db) => db.CtMgtWgAllocationRules;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMhsToCph> GetCtMhsToCphs([Service] CtsTransactionsGraphQLDbContext db) => db.CtMhsToCphs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovHst> GetCtMovHsts([Service] CtsTransactionsGraphQLDbContext db) => db.CtMovHsts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovtCorrSummError> GetCtMovtCorrSummErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtMovtCorrSummErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovtCorrectSummary> GetCtMovtCorrectSummaries([Service] CtsTransactionsGraphQLDbContext db) => db.CtMovtCorrectSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMsgtxt> GetCtMsgtxts([Service] CtsTransactionsGraphQLDbContext db) => db.CtMsgtxts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtNonWorkingDay> GetCtNonWorkingDays([Service] CtsTransactionsGraphQLDbContext db) => db.CtNonWorkingDays;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParamGroup> GetCtParamGroups([Service] CtsTransactionsGraphQLDbContext db) => db.CtParamGroups;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParamHeader> GetCtParamHeaders([Service] CtsTransactionsGraphQLDbContext db) => db.CtParamHeaders;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParamValue> GetCtParamValues([Service] CtsTransactionsGraphQLDbContext db) => db.CtParamValues;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParamValueGroup> GetCtParamValueGroups([Service] CtsTransactionsGraphQLDbContext db) => db.CtParamValueGroups;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPartiesFaker> GetCtPartiesFakers([Service] CtsTransactionsGraphQLDbContext db) => db.CtPartiesFakers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParty> GetCtParties([Service] CtsTransactionsGraphQLDbContext db) => db.CtParties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPpafGrouping> GetCtPpafGroupings([Service] CtsTransactionsGraphQLDbContext db) => db.CtPpafGroupings;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPreprintedAppnForm> GetCtPreprintedAppnForms([Service] CtsTransactionsGraphQLDbContext db) => db.CtPreprintedAppnForms;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtProbityCheck> GetCtProbityChecks([Service] CtsTransactionsGraphQLDbContext db) => db.CtProbityChecks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPs9999AhdbDatum> GetCtPs9999AhdbData([Service] CtsTransactionsGraphQLDbContext db) => db.CtPs9999AhdbData;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPs9999AhdbMovHistory> GetCtPs9999AhdbMovHistories([Service] CtsTransactionsGraphQLDbContext db) => db.CtPs9999AhdbMovHistories;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRecdApplicationError> GetCtRecdApplicationErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtRecdApplicationErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRecdMovementError> GetCtRecdMovementErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtRecdMovementErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtReceivedApplication> GetCtReceivedApplications([Service] CtsTransactionsGraphQLDbContext db) => db.CtReceivedApplications;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtReceivedMovement> GetCtReceivedMovements([Service] CtsTransactionsGraphQLDbContext db) => db.CtReceivedMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRegisteredAnimal> GetCtRegisteredAnimals([Service] CtsTransactionsGraphQLDbContext db) => db.CtRegisteredAnimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRegisteredMovement> GetCtRegisteredMovements([Service] CtsTransactionsGraphQLDbContext db) => db.CtRegisteredMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtResetToExtract> GetCtResetToExtracts([Service] CtsTransactionsGraphQLDbContext db) => db.CtResetToExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSbcsExt> GetCtSbcsExts([Service] CtsTransactionsGraphQLDbContext db) => db.CtSbcsExts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtScheme> GetCtSchemes([Service] CtsTransactionsGraphQLDbContext db) => db.CtSchemes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageFile> GetCtStageFiles([Service] CtsTransactionsGraphQLDbContext db) => db.CtStageFiles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageLock> GetCtStageLocks([Service] CtsTransactionsGraphQLDbContext db) => db.CtStageLocks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageMessage> GetCtStageMessages([Service] CtsTransactionsGraphQLDbContext db) => db.CtStageMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSublocationType> GetCtSublocationTypes([Service] CtsTransactionsGraphQLDbContext db) => db.CtSublocationTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspAnimalError> GetCtSuspAnimalErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspAnimalErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspCmMeasureResult> GetCtSuspCmMeasureResults([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspCmMeasureResults;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspConditionMarker> GetCtSuspConditionMarkers([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspConditionMarkers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspMovementError> GetCtSuspMovementErrors([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspMovementErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspendedAnimal> GetCtSuspendedAnimals([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspendedAnimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspendedMovement> GetCtSuspendedMovements([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspendedMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspenseCharAllocRule> GetCtSuspenseCharAllocRules([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspenseCharAllocRules;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspenseWgAllocRule> GetCtSuspenseWgAllocRules([Service] CtsTransactionsGraphQLDbContext db) => db.CtSuspenseWgAllocRules;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtValidApplication> GetCtValidApplications([Service] CtsTransactionsGraphQLDbContext db) => db.CtValidApplications;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWebUser> GetCtWebUsers([Service] CtsTransactionsGraphQLDbContext db) => db.CtWebUsers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgAutoallocation> GetCtWgAutoallocations([Service] CtsTransactionsGraphQLDbContext db) => db.CtWgAutoallocations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgSuperAssignment> GetCtWgSuperAssignments([Service] CtsTransactionsGraphQLDbContext db) => db.CtWgSuperAssignments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgUserAssignment> GetCtWgUserAssignments([Service] CtsTransactionsGraphQLDbContext db) => db.CtWgUserAssignments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWorkgroup> GetCtWorkgroups([Service] CtsTransactionsGraphQLDbContext db) => db.CtWorkgroups;
   }