// <auto-generated />
// Generated using the HotChocolate GraphQL code generator (see CADS Tools)
// .\cads-tools\codegen\graph-query-generate\Generate-GraphQuery-Resolvers.ps1
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsAudit.Contexts;
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsAudit.Entities;
using HotChocolate;
using HotChocolate.Data;
using HotChocolate.Types;
using System.Linq;

namespace Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.CtsAudit.Queries;

[ExtendObjectType("Query")]
public partial class CtsAuditGraphQuery
{
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAddress> GetCtAddresses([Service] CtsAuditGraphQLDbContext db) => db.CtAddresses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalChange> GetCtAnimalChanges([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalChanges;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalClaim> GetCtAnimalClaims([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalClaims;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalCorrSummError> GetCtAnimalCorrSummErrors([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalCorrSummErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalCorrectSummary> GetCtAnimalCorrectSummaries([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalCorrectSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalIdentifier> GetCtAnimalIdentifiers([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalRelationship> GetCtAnimalRelationships([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalRelationships;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtAnimalStatus> GetCtAnimalStatuses([Service] CtsAuditGraphQLDbContext db) => db.CtAnimalStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtApplicStatus> GetCtApplicStatuses([Service] CtsAuditGraphQLDbContext db) => db.CtApplicStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtApplicationLateDay> GetCtApplicationLateDays([Service] CtsAuditGraphQLDbContext db) => db.CtApplicationLateDays;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtract> GetCtClaExtracts([Service] CtsAuditGraphQLDbContext db) => db.CtClaExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtractDetail> GetCtClaExtractDetails([Service] CtsAuditGraphQLDbContext db) => db.CtClaExtractDetails;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaExtractDm> GetCtClaExtractDms([Service] CtsAuditGraphQLDbContext db) => db.CtClaExtractDms;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaMiniDetail> GetCtClaMiniDetails([Service] CtsAuditGraphQLDbContext db) => db.CtClaMiniDetails;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtClaMiniExtract> GetCtClaMiniExtracts([Service] CtsAuditGraphQLDbContext db) => db.CtClaMiniExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCmMeasuresResult> GetCtCmMeasuresResults([Service] CtsAuditGraphQLDbContext db) => db.CtCmMeasuresResults;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCommsAddress> GetCtCommsAddresses([Service] CtsAuditGraphQLDbContext db) => db.CtCommsAddresses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionMarker> GetCtConditionMarkers([Service] CtsAuditGraphQLDbContext db) => db.CtConditionMarkers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtConditionMarkerError> GetCtConditionMarkerErrors([Service] CtsAuditGraphQLDbContext db) => db.CtConditionMarkerErrors;
    public IQueryable<CtCps167Report> GetCtCps167Reports([Service] CtsAuditGraphQLDbContext db) => db.CtCps167Reports;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtCtsUser> GetCtCtsUsers([Service] CtsAuditGraphQLDbContext db) => db.CtCtsUsers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartag> GetCtEartags([Service] CtsAuditGraphQLDbContext db) => db.CtEartags;

    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEartagStaging> GetCtEartagStagings([Service] CtsAuditGraphQLDbContext db) => db.CtEartagStagings;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtElectronicIdentifier> GetCtElectronicIdentifiers([Service] CtsAuditGraphQLDbContext db) => db.CtElectronicIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEmailLog> GetCtEmailLogs([Service] CtsAuditGraphQLDbContext db) => db.CtEmailLogs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportFile> GetCtEreportFiles([Service] CtsAuditGraphQLDbContext db) => db.CtEreportFiles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportLoadMessage> GetCtEreportLoadMessages([Service] CtsAuditGraphQLDbContext db) => db.CtEreportLoadMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportLock> GetCtEreportLocks([Service] CtsAuditGraphQLDbContext db) => db.CtEreportLocks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtEreportProcessMessage> GetCtEreportProcessMessages([Service] CtsAuditGraphQLDbContext db) => db.CtEreportProcessMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtExtCetdEartag> GetCtExtCetdEartags([Service] CtsAuditGraphQLDbContext db) => db.CtExtCetdEartags;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtInsertUpdateLog> GetCtInsertUpdateLogs([Service] CtsAuditGraphQLDbContext db) => db.CtInsertUpdateLogs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtIssuedDocument> GetCtIssuedDocuments([Service] CtsAuditGraphQLDbContext db) => db.CtIssuedDocuments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLabelRequest> GetCtLabelRequests([Service] CtsAuditGraphQLDbContext db) => db.CtLabelRequests;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLabelSummary> GetCtLabelSummaries([Service] CtsAuditGraphQLDbContext db) => db.CtLabelSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLetter> GetCtLetters([Service] CtsAuditGraphQLDbContext db) => db.CtLetters;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocation> GetCtLocations([Service] CtsAuditGraphQLDbContext db) => db.CtLocations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationIdentifier> GetCtLocationIdentifiers([Service] CtsAuditGraphQLDbContext db) => db.CtLocationIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationPartyRel> GetCtLocationPartyRels([Service] CtsAuditGraphQLDbContext db) => db.CtLocationPartyRels;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationRelationship> GetCtLocationRelationships([Service] CtsAuditGraphQLDbContext db) => db.CtLocationRelationships;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocationsFaker> GetCtLocationsFakers([Service] CtsAuditGraphQLDbContext db) => db.CtLocationsFakers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtLocrestrictionstoanimal> GetCtLocrestrictionstoanimals([Service] CtsAuditGraphQLDbContext db) => db.CtLocrestrictionstoanimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMgtControlError> GetCtMgtControlErrors([Service] CtsAuditGraphQLDbContext db) => db.CtMgtControlErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMhsToCph> GetCtMhsToCphs([Service] CtsAuditGraphQLDbContext db) => db.CtMhsToCphs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovHst> GetCtMovHsts([Service] CtsAuditGraphQLDbContext db) => db.CtMovHsts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovtCorrSummError> GetCtMovtCorrSummErrors([Service] CtsAuditGraphQLDbContext db) => db.CtMovtCorrSummErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtMovtCorrectSummary> GetCtMovtCorrectSummaries([Service] CtsAuditGraphQLDbContext db) => db.CtMovtCorrectSummaries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPartiesFaker> GetCtPartiesFakers([Service] CtsAuditGraphQLDbContext db) => db.CtPartiesFakers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtParty> GetCtParties([Service] CtsAuditGraphQLDbContext db) => db.CtParties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPpafGrouping> GetCtPpafGroupings([Service] CtsAuditGraphQLDbContext db) => db.CtPpafGroupings;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPreprintedAppnForm> GetCtPreprintedAppnForms([Service] CtsAuditGraphQLDbContext db) => db.CtPreprintedAppnForms;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPs9999AhdbDatum> GetCtPs9999AhdbData([Service] CtsAuditGraphQLDbContext db) => db.CtPs9999AhdbData;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtPs9999AhdbMovHistory> GetCtPs9999AhdbMovHistories([Service] CtsAuditGraphQLDbContext db) => db.CtPs9999AhdbMovHistories;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRecdApplicationError> GetCtRecdApplicationErrors([Service] CtsAuditGraphQLDbContext db) => db.CtRecdApplicationErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRecdMovementError> GetCtRecdMovementErrors([Service] CtsAuditGraphQLDbContext db) => db.CtRecdMovementErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtReceivedApplication> GetCtReceivedApplications([Service] CtsAuditGraphQLDbContext db) => db.CtReceivedApplications;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtReceivedMovement> GetCtReceivedMovements([Service] CtsAuditGraphQLDbContext db) => db.CtReceivedMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRegisteredAnimal> GetCtRegisteredAnimals([Service] CtsAuditGraphQLDbContext db) => db.CtRegisteredAnimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtRegisteredMovement> GetCtRegisteredMovements([Service] CtsAuditGraphQLDbContext db) => db.CtRegisteredMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtResetToExtract> GetCtResetToExtracts([Service] CtsAuditGraphQLDbContext db) => db.CtResetToExtracts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSbcsExt> GetCtSbcsExts([Service] CtsAuditGraphQLDbContext db) => db.CtSbcsExts;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageFile> GetCtStageFiles([Service] CtsAuditGraphQLDbContext db) => db.CtStageFiles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageLock> GetCtStageLocks([Service] CtsAuditGraphQLDbContext db) => db.CtStageLocks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtStageMessage> GetCtStageMessages([Service] CtsAuditGraphQLDbContext db) => db.CtStageMessages;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspAnimalError> GetCtSuspAnimalErrors([Service] CtsAuditGraphQLDbContext db) => db.CtSuspAnimalErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspCmMeasureResult> GetCtSuspCmMeasureResults([Service] CtsAuditGraphQLDbContext db) => db.CtSuspCmMeasureResults;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspConditionMarker> GetCtSuspConditionMarkers([Service] CtsAuditGraphQLDbContext db) => db.CtSuspConditionMarkers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspMovementError> GetCtSuspMovementErrors([Service] CtsAuditGraphQLDbContext db) => db.CtSuspMovementErrors;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspendedAnimal> GetCtSuspendedAnimals([Service] CtsAuditGraphQLDbContext db) => db.CtSuspendedAnimals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtSuspendedMovement> GetCtSuspendedMovements([Service] CtsAuditGraphQLDbContext db) => db.CtSuspendedMovements;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtValidApplication> GetCtValidApplications([Service] CtsAuditGraphQLDbContext db) => db.CtValidApplications;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWebUser> GetCtWebUsers([Service] CtsAuditGraphQLDbContext db) => db.CtWebUsers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgAutoallocation> GetCtWgAutoallocations([Service] CtsAuditGraphQLDbContext db) => db.CtWgAutoallocations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgSuperAssignment> GetCtWgSuperAssignments([Service] CtsAuditGraphQLDbContext db) => db.CtWgSuperAssignments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWgUserAssignment> GetCtWgUserAssignments([Service] CtsAuditGraphQLDbContext db) => db.CtWgUserAssignments;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtWorkgroup> GetCtWorkgroups([Service] CtsAuditGraphQLDbContext db) => db.CtWorkgroups;
}