// <auto-generated />
// Generated using the HotChocolate GraphQL code generator (see CADS Tools)
// .\cads-tools\codegen\graph-query-generate\Generate-GraphQuery-Resolvers.ps1
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.Cads.Contexts;
using Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.Cads.Entities;
using HotChocolate;
using HotChocolate.Data;
using HotChocolate.Types;
using System.Linq;

namespace Cads.Cds.SystemAdmin.Infrastructure.GraphQL.Schemas.Cads.Queries;

[ExtendObjectType("Query")]
public partial class CadsGraphQuery
{   
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<Animal> GetAnimals([Service] CadsGraphQLDbContext db) => db.Animals;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalBirth> GetAnimalBirths([Service] CadsGraphQLDbContext db) => db.AnimalBirths;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalBreed> GetAnimalBreeds([Service] CadsGraphQLDbContext db) => db.AnimalBreeds;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalBreedState> GetAnimalBreedStates([Service] CadsGraphQLDbContext db) => db.AnimalBreedStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollective> GetAnimalCollectives([Service] CadsGraphQLDbContext db) => db.AnimalCollectives;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveDeath> GetAnimalCollectiveDeaths([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveDeaths;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveParty> GetAnimalCollectiveParties([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveParties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveRef> GetAnimalCollectiveRefs([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveRefs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveRegistration> GetAnimalCollectiveRegistrations([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveRegistrations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveRole> GetAnimalCollectiveRoles([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveRoles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalCollectiveState> GetAnimalCollectiveStates([Service] CadsGraphQLDbContext db) => db.AnimalCollectiveStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalDeath> GetAnimalDeaths([Service] CadsGraphQLDbContext db) => db.AnimalDeaths;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalDeathReason> GetAnimalDeathReasons([Service] CadsGraphQLDbContext db) => db.AnimalDeathReasons;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalGenotype> GetAnimalGenotypes([Service] CadsGraphQLDbContext db) => db.AnimalGenotypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalIdentifier> GetAnimalIdentifiers([Service] CadsGraphQLDbContext db) => db.AnimalIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalLostOrStolenState> GetAnimalLostOrStolenStates([Service] CadsGraphQLDbContext db) => db.AnimalLostOrStolenStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalLostOrStolenStatus> GetAnimalLostOrStolenStatuses([Service] CadsGraphQLDbContext db) => db.AnimalLostOrStolenStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalMark> GetAnimalMarks([Service] CadsGraphQLDbContext db) => db.AnimalMarks;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalNoticeToIdentify> GetAnimalNoticeToIdentifies([Service] CadsGraphQLDbContext db) => db.AnimalNoticeToIdentifies;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalOriginalIdentifierType> GetAnimalOriginalIdentifierTypes([Service] CadsGraphQLDbContext db) => db.AnimalOriginalIdentifierTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalParty> GetAnimalParties([Service] CadsGraphQLDbContext db) => db.AnimalParties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalPartyRef> GetAnimalPartyRefs([Service] CadsGraphQLDbContext db) => db.AnimalPartyRefs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalProductionType> GetAnimalProductionTypes([Service] CadsGraphQLDbContext db) => db.AnimalProductionTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalRegistrationCategory> GetAnimalRegistrationCategories([Service] CadsGraphQLDbContext db) => db.AnimalRegistrationCategories;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalResolutionType> GetAnimalResolutionTypes([Service] CadsGraphQLDbContext db) => db.AnimalResolutionTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalRole> GetAnimalRoles([Service] CadsGraphQLDbContext db) => db.AnimalRoles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalSex> GetAnimalSexes([Service] CadsGraphQLDbContext db) => db.AnimalSexes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalSiteRef> GetAnimalSiteRefs([Service] CadsGraphQLDbContext db) => db.AnimalSiteRefs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalSpeciesProductionType> GetAnimalSpeciesProductionTypes([Service] CadsGraphQLDbContext db) => db.AnimalSpeciesProductionTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalSpecy> GetAnimalSpecies([Service] CadsGraphQLDbContext db) => db.AnimalSpecies;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalState> GetAnimalStates([Service] CadsGraphQLDbContext db) => db.AnimalStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalStatus> GetAnimalStatuses([Service] CadsGraphQLDbContext db) => db.AnimalStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<AnimalUnregisteredParent> GetAnimalUnregisteredParents([Service] CadsGraphQLDbContext db) => db.AnimalUnregisteredParents;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtsFileImport> GetCtsFileImports([Service] CadsGraphQLDbContext db) => db.CtsFileImports;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtsFileImportStatus> GetCtsFileImportStatuses([Service] CadsGraphQLDbContext db) => db.CtsFileImportStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtsFileImportsLog> GetCtsFileImportsLogs([Service] CadsGraphQLDbContext db) => db.CtsFileImportsLogs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<CtsFileProcessingStatus> GetCtsFileProcessingStatuses([Service] CadsGraphQLDbContext db) => db.CtsFileProcessingStatuses;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<Entities.Location> GetLocations([Service] CadsGraphQLDbContext db) => db.Locations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationActivity> GetLocationActivities([Service] CadsGraphQLDbContext db) => db.LocationActivities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationAssociatedSite> GetLocationAssociatedSites([Service] CadsGraphQLDbContext db) => db.LocationAssociatedSites;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationAssociatedSiteType> GetLocationAssociatedSiteTypes([Service] CadsGraphQLDbContext db) => db.LocationAssociatedSiteTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationCountry> GetLocationCountries([Service] CadsGraphQLDbContext db) => db.LocationCountries;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationPartyRef> GetLocationPartyRefs([Service] CadsGraphQLDbContext db) => db.LocationPartyRefs;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationPostcode> GetLocationPostcodes([Service] CadsGraphQLDbContext db) => db.LocationPostcodes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSite> GetLocationSites([Service] CadsGraphQLDbContext db) => db.LocationSites;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteActivity> GetLocationSiteActivities([Service] CadsGraphQLDbContext db) => db.LocationSiteActivities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteIdentifier> GetLocationSiteIdentifiers([Service] CadsGraphQLDbContext db) => db.LocationSiteIdentifiers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteIdentifierType> GetLocationSiteIdentifierTypes([Service] CadsGraphQLDbContext db) => db.LocationSiteIdentifierTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteParty> GetLocationSiteParties([Service] CadsGraphQLDbContext db) => db.LocationSiteParties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteRole> GetLocationSiteRoles([Service] CadsGraphQLDbContext db) => db.LocationSiteRoles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteSource> GetLocationSiteSources([Service] CadsGraphQLDbContext db) => db.LocationSiteSources;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteState> GetLocationSiteStates([Service] CadsGraphQLDbContext db) => db.LocationSiteStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteType> GetLocationSiteTypes([Service] CadsGraphQLDbContext db) => db.LocationSiteTypes;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<LocationSiteTypeActivity> GetLocationSiteTypeActivities([Service] CadsGraphQLDbContext db) => db.LocationSiteTypeActivities;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiEffectiveReportAllPermission> GetMiEffectiveReportAllPermissions([Service] CadsGraphQLDbContext db) => db.MiEffectiveReportAllPermissions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiEffectiveReportPermission> GetMiEffectiveReportPermissions([Service] CadsGraphQLDbContext db) => db.MiEffectiveReportPermissions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiPermission> GetMiPermissions([Service] CadsGraphQLDbContext db) => db.MiPermissions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiReport> GetMiReports([Service] CadsGraphQLDbContext db) => db.MiReports;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiReportGroup> GetMiReportGroups([Service] CadsGraphQLDbContext db) => db.MiReportGroups;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiRole> GetMiRoles([Service] CadsGraphQLDbContext db) => db.MiRoles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiRoleReportPermission> GetMiRoleReportPermissions([Service] CadsGraphQLDbContext db) => db.MiRoleReportPermissions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiUser> GetMiUsers([Service] CadsGraphQLDbContext db) => db.MiUsers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiUserReportPermission> GetMiUserReportPermissions([Service] CadsGraphQLDbContext db) => db.MiUserReportPermissions;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<MiUserRole> GetMiUserRoles([Service] CadsGraphQLDbContext db) => db.MiUserRoles;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<Party> GetParties([Service] CadsGraphQLDbContext db) => db.Parties;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<PartyHaulier> GetPartyHauliers([Service] CadsGraphQLDbContext db) => db.PartyHauliers;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<PartyLocation> GetPartyLocations([Service] CadsGraphQLDbContext db) => db.PartyLocations;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<PartySpecy> GetPartySpecies([Service] CadsGraphQLDbContext db) => db.PartySpecies;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<PartyState> GetPartyStates([Service] CadsGraphQLDbContext db) => db.PartyStates;
    [UsePaging]     // Enables pagination
    [UseProjection] // Allows selecting nested fields
    [UseFiltering]  // Enables filtering
    [UseSorting]    // Enables sorting
    public IQueryable<PartyType> GetPartyTypes([Service] CadsGraphQLDbContext db) => db.PartyTypes;}
